@template.layout.main(
title="Students",
content = @`
    <h2 class="text-center mb-4 mt-4">2024 Summer Swimming Lessons</h2>
    <p class="text-center mb-4 lh-lg">
        Classes are on Monday to Thursday:<br>
        Session 1: June 17 - June 27<br>
        Session 2: July 8 - July 18<br>
        Session 3: July 22 - August 1<br>
        Session 4: August 5 - August 15<br>
        <a class="btn btn-success mt-4" href="/register" role="button">Register</a>
    </p>
`)